---
  extends: [semistandard-react, prettier, prettier/react, plugin:jsx-a11y/recommended]
  plugins: [prettier, jsx-a11y]
  settings:
    react:
      version: detect
  overrides:
    files:
      - "**/*.spec.js"
    env:
      jest: true
    plugins:
      - "jest"
