---
  extends:
    - plugin:react/recommended
    - plugin:react-hooks/recommended
    - plugin:prettier/recommended
    - plugin:jsx-a11y/recommended
  plugins: [prettier, jsx-a11y]
  env:
    es6: true
    node: true
    browser: true
  parserOptions:
    ecmaVersion: 8
    sourceType: 'module'
    ecmaFeatures:
      jsx: true
  settings:
    react:
      version: detect
  overrides:
    - files:
        - "**/*.spec.js"
      env:
        jest: true
      plugins:
        - "jest"
